"use client";

import { Fragment, useMemo, useRef, useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";

import { FieldError } from "@/components/field-error";
import { useLocale } from "@/components/locale-provider";
import { Button } from "@/components/ui/button";
import { toast } from "@/lib/toast";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { useGuestFilters } from "@/features/guests/hooks/use-guest-filters";
import type { GuestInput } from "@/features/guests/types/guest";
import { canEditGuests } from "@/lib/access-control";
import type {
  GuestView,
  InvitationGroupView,
  UserRole,
} from "@/lib/planner-domain";
import { apiClient } from "@/lib/api-client";

const guestFormSchema = z.object({
  firstName: z.string().min(1),
  lastName: z.string().min(1),
  side: z.enum(["BRIDE", "GROOM", "FAMILY", "FRIENDS"]),
  rsvpStatus: z.enum(["PENDING", "ATTENDING", "DECLINED"]),
  paymentCoverage: z.enum(["FULL", "HALF"]),
  invitationReceived: z.boolean(),
  transportToVenue: z.boolean(),
  transportFromVenue: z.boolean(),
  dietaryRestrictions: z.array(z.enum(["NONE", "VEGETARIAN", "VEGAN"])),
  dietaryRestriction: z.enum(["NONE", "VEGETARIAN", "VEGAN"]),
  email: z.string().email().or(z.literal("")),
  phone: z.string().min(6).or(z.literal("")),
  notes: z.string(),
  groupName: z.string(),
  invitedGuestCount: z.coerce.number().int().min(1).max(10),
});

type GuestFormValues = GuestInput & {
  dietaryRestriction: "NONE" | "VEGETARIAN" | "VEGAN";
};

const emptyGuestForm: GuestFormValues = {
  firstName: "",
  lastName: "",
  side: "BRIDE",
  rsvpStatus: "PENDING",
  paymentCoverage: "FULL",
  invitationReceived: false,
  transportToVenue: false,
  transportFromVenue: false,
  dietaryRestrictions: ["NONE"],
  dietaryRestriction: "NONE",
  email: "",
  phone: "",
  notes: "",
  groupName: "",
  invitedGuestCount: 1,
};

const isAutoGeneratedGroupName = (groupName?: string | null) =>
  Boolean(groupName?.trim().match(/^(grupa|group)\s+\d+$/i));

const exportToExcel = async (
  guests: GuestView[],
  messages: Record<string, string>,
) => {
  const XLSX = await import("xlsx");
  const rows = guests.map((g) => ({
    [messages.name]: g.fullName,
    [messages.rsvp]: g.rsvpStatus,
    [messages.side]: g.side,
    [messages.groupName]: g.groupName ?? "",
    [messages.diet]: g.dietaryRestrictions.join(", "),
    [messages.email]: g.email,
    [messages.phone]: g.phone,
    [messages.table]: g.tableName ?? "",
    [messages.notesLabel]: g.notes,
  }));
  const ws = XLSX.utils.json_to_sheet(rows);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, "Guests");
  XLSX.writeFile(wb, "guests.xlsx");
};

const exportToPdf = (guests: GuestView[], messages: Record<string, string>) => {
  const win = window.open("", "_blank");
  if (!win) return;
  const rows = guests
    .map(
      (g) =>
        `<tr><td>${g.fullName}</td><td>${g.rsvpStatus}</td><td>${g.side}</td><td>${g.groupName ?? ""}</td><td>${g.email}</td><td>${g.tableName ?? ""}</td></tr>`,
    )
    .join("");
  win.document
    .write(`<!DOCTYPE html><html><head><title>${messages.exportTitle}</title>
    <style>body{font-family:system-ui;margin:2rem}table{width:100%;border-collapse:collapse}th,td{border:1px solid #ccc;padding:6px 10px;text-align:left;font-size:13px}th{background:#f5f5f5}</style></head><body>
    <h1>${messages.exportTitle}</h1>
    <table><thead><tr><th>${messages.name}</th><th>${messages.rsvp}</th><th>${messages.side}</th><th>${messages.groupName}</th><th>${messages.email}</th><th>${messages.table}</th></tr></thead><tbody>${rows}</tbody></table>
    <script>window.print();window.close();<\/script></body></html>`);
  win.document.close();
};

export const GuestManager = ({
  initialGuests,
  initialGroups,
  viewerRole,
}: {
  initialGuests: GuestView[];
  initialGroups: InvitationGroupView[];
  viewerRole: UserRole;
}) => {
  const { messages } = useLocale();
  const canEdit = canEditGuests(viewerRole);
  const [guests, setGuests] = useState(initialGuests);
  const [groups, setGroups] = useState(initialGroups);
  const [selectedGuest, setSelectedGuest] = useState<GuestView | null>(null);
  const [search, setSearch] = useState("");
  const [side, setSide] = useState("ALL");
  const [group, setGroup] = useState("ALL");
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set());
  const [bulkRsvp, setBulkRsvp] = useState<
    "PENDING" | "ATTENDING" | "DECLINED"
  >("ATTENDING");
  const formRef = useRef<HTMLDivElement | null>(null);
  const filteredGuests = useGuestFilters(guests, search, side, group);

  const uniqueGroups = useMemo(() => {
    const groups = new Set<string>();
    for (const g of guests) {
      if (g.groupName) groups.add(g.groupName);
    }
    return [...groups].sort();
  }, [guests]);

  const {
    register,
    handleSubmit,
    reset,
    formState: { errors, isSubmitting },
  } = useForm<GuestFormValues>({
    defaultValues: emptyGuestForm,
    resolver: zodResolver(guestFormSchema) as never,
  });

  const onSubmit = handleSubmit(async (values: GuestFormValues) => {
    try {
      const payload: GuestInput = {
        ...values,
        dietaryRestrictions: [values.dietaryRestriction],
      };

      if (selectedGuest) {
        const updated = await apiClient<GuestView>(
          `/api/guests/${selectedGuest.id}`,
          {
            method: "PATCH",
            body: JSON.stringify(payload),
          },
        );
        setGuests((current) =>
          current.map((guest) => (guest.id === updated.id ? updated : guest)),
        );
      } else {
        const created = await apiClient<GuestView>("/api/guests", {
          method: "POST",
          body: JSON.stringify(payload),
        });
        setGuests((current) => [...current, created]);
      }

      try {
        setGroups(await apiClient<InvitationGroupView[]>("/api/guest-groups"));
      } catch {
        /* ignore */
      }

      setSelectedGuest(null);
      reset(emptyGuestForm);
    } catch {
      toast.error(messages.common.actionError);
    }
  });

  const handleEdit = (guest: GuestView) => {
    setSelectedGuest(guest);
    formRef.current?.scrollIntoView({ behavior: "smooth", block: "start" });
    reset({
      firstName: guest.firstName,
      lastName: guest.lastName,
      side: guest.side,
      rsvpStatus: guest.rsvpStatus,
      paymentCoverage: guest.paymentCoverage,
      invitationReceived: guest.invitationReceived,
      transportToVenue: guest.transportToVenue,
      transportFromVenue: guest.transportFromVenue,
      dietaryRestrictions: guest.dietaryRestrictions as Array<
        "NONE" | "VEGETARIAN" | "VEGAN"
      >,
      dietaryRestriction:
        (guest.dietaryRestrictions[0] as "NONE" | "VEGETARIAN" | "VEGAN") ??
        "NONE",
      email: guest.email,
      phone: guest.phone,
      notes: guest.notes,
      groupName: guest.groupName ?? "",
      invitedGuestCount: guest.invitedGuestCount ?? 1,
    });
  };

  const handleDelete = async (guestId: string) => {
    if (!window.confirm(messages.common.confirmDelete)) {
      return;
    }
    try {
      await apiClient<{ guestId: string }>(`/api/guests/${guestId}`, {
        method: "DELETE",
      });
      setGuests((current) => current.filter((guest) => guest.id !== guestId));
    } catch {
      toast.error(messages.common.actionError);
    }
  };

  const handleRsvpToggle = async (guest: GuestView) => {
    try {
      const updated = await apiClient<GuestView>(`/api/guests/${guest.id}`, {
        method: "PATCH",
        body: JSON.stringify({
          ...guest,
          rsvpStatus:
            guest.rsvpStatus === "ATTENDING" ? "PENDING" : "ATTENDING",
        }),
      });
      setGuests((current) =>
        current.map((candidate) =>
          candidate.id === updated.id ? updated : candidate,
        ),
      );
    } catch {
      toast.error(messages.common.actionError);
    }
  };

  const toggleSelected = (id: string) => {
    setSelectedIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  };

  const toggleAll = () => {
    if (selectedIds.size === filteredGuests.length) {
      setSelectedIds(new Set());
    } else {
      setSelectedIds(new Set(filteredGuests.map((g) => g.id)));
    }
  };

  const refreshGuests = async () => {
    try {
      const fresh = await apiClient<GuestView[]>("/api/guests");
      setGuests(fresh);
      const freshGroups =
        await apiClient<InvitationGroupView[]>("/api/guest-groups");
      setGroups(freshGroups);
    } catch {
      /* ignore */
    }
  };

  const handleBulkRsvp = async () => {
    try {
      await apiClient("/api/guests/bulk", {
        method: "POST",
        body: JSON.stringify({
          action: "update",
          guestIds: [...selectedIds],
          updates: { rsvpStatus: bulkRsvp },
        }),
      });
      await refreshGuests();
      setSelectedIds(new Set());
    } catch {
      toast.error(messages.common.actionError);
    }
  };

  const handleBulkAssignGroup = async () => {
    try {
      await apiClient("/api/guests/bulk", {
        method: "POST",
        body: JSON.stringify({
          action: "update",
          guestIds: [...selectedIds],
          updates: {
            groupName: nextGroupName,
            invitedGuestCount: selectedIds.size,
          },
        }),
      });
      await refreshGuests();
      setSelectedIds(new Set());
    } catch {
      toast.error(messages.common.actionError);
    }
  };

  const handleBulkUngroup = async () => {
    try {
      await apiClient("/api/guests/bulk", {
        method: "POST",
        body: JSON.stringify({
          action: "update",
          guestIds: [...selectedIds],
          updates: { groupName: "" },
        }),
      });
      await refreshGuests();
      setSelectedIds(new Set());
    } catch {
      toast.error(messages.common.actionError);
    }
  };

  const handleBulkDelete = async () => {
    if (!window.confirm(messages.common.confirmDelete)) return;
    try {
      await apiClient("/api/guests/bulk", {
        method: "POST",
        body: JSON.stringify({
          action: "delete",
          guestIds: [...selectedIds],
        }),
      });
      await refreshGuests();
      setSelectedIds(new Set());
    } catch {
      toast.error(messages.common.actionError);
    }
  };

  const exportMessages = {
    name: messages.guests.name,
    rsvp: messages.guests.rsvp,
    side: messages.guests.side,
    groupName: messages.guests.groupName,
    diet: messages.guests.diet,
    email: messages.guests.email,
    phone: messages.guests.phone,
    table: messages.guests.table,
    notesLabel: messages.guests.notesLabel,
    exportTitle: messages.guests.exportTitle,
  };

  const columnCount = canEdit ? 13 : 12;
  const usedGroupNumbers = new Set(
    guests
      .map((guest) => guest.groupName ?? "")
      .map((groupName) => {
        const match = groupName.match(/(\d+)/);
        return match ? Number(match[1]) : null;
      })
      .filter((value): value is number => value !== null),
  );
  let nextGroupNumber = 1;
  while (usedGroupNumbers.has(nextGroupNumber)) {
    nextGroupNumber += 1;
  }
  const nextGroupName = `${messages.guests.groupPrefix} ${nextGroupNumber}`;
  const guestSummary = useMemo(
    () => ({
      totalGuests: guests.length,
      groupedGuests: guests.filter((guest) => guest.groupName).length,
      attendingGuests: guests.filter(
        (guest) => guest.rsvpStatus === "ATTENDING",
      ).length,
      groupCount: groups.length,
    }),
    [groups.length, guests],
  );
  const visibleGroups = useMemo(
    () =>
      groups.filter((groupItem) => !isAutoGeneratedGroupName(groupItem.name)),
    [groups],
  );

  return (
    <div className="space-y-6">
      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <div className="rounded-[1.8rem] border border-white/70 bg-[linear-gradient(135deg,rgba(255,255,255,0.86),rgba(255,244,229,0.82),rgba(255,237,244,0.78))] p-5 shadow-[0_22px_65px_rgba(233,60,172,0.1)]">
          <p className="text-xs uppercase tracking-[0.24em] text-[var(--color-dusty-rose)]">
            {messages.guests.summaryTotal}
          </p>
          <p className="mt-3 font-display text-4xl text-[var(--color-ink)]">
            {guestSummary.totalGuests}
          </p>
          <p className="mt-2 text-sm text-[var(--color-muted-copy)]">
            {messages.guests.summaryTotalHelp}
          </p>
        </div>
        <div className="rounded-[1.8rem] border border-white/70 bg-[linear-gradient(135deg,rgba(255,255,255,0.86),rgba(245,255,244,0.82),rgba(255,249,233,0.8))] p-5 shadow-[0_22px_65px_rgba(76,154,50,0.08)]">
          <p className="text-xs uppercase tracking-[0.24em] text-[var(--color-dusty-rose)]">
            {messages.guests.summaryAttending}
          </p>
          <p className="mt-3 font-display text-4xl text-[var(--color-ink)]">
            {guestSummary.attendingGuests}
          </p>
          <p className="mt-2 text-sm text-[var(--color-muted-copy)]">
            {messages.guests.summaryAttendingHelp}
          </p>
        </div>
        <div className="rounded-[1.8rem] border border-white/70 bg-[linear-gradient(135deg,rgba(255,255,255,0.88),rgba(244,247,255,0.82),rgba(255,240,246,0.78))] p-5 shadow-[0_22px_65px_rgba(49,72,216,0.08)]">
          <p className="text-xs uppercase tracking-[0.24em] text-[var(--color-dusty-rose)]">
            {messages.guests.summaryGrouped}
          </p>
          <p className="mt-3 font-display text-4xl text-[var(--color-ink)]">
            {guestSummary.groupedGuests}
          </p>
          <p className="mt-2 text-sm text-[var(--color-muted-copy)]">
            {messages.guests.summaryGroupedHelp}
          </p>
        </div>
        <div className="rounded-[1.8rem] border border-white/70 bg-[linear-gradient(135deg,rgba(255,255,255,0.88),rgba(255,240,246,0.82),rgba(255,249,233,0.8))] p-5 shadow-[0_22px_65px_rgba(255,122,33,0.08)]">
          <p className="text-xs uppercase tracking-[0.24em] text-[var(--color-dusty-rose)]">
            {messages.guests.summaryGroups}
          </p>
          <p className="mt-3 font-display text-4xl text-[var(--color-ink)]">
            {guestSummary.groupCount}
          </p>
          <p className="mt-2 text-sm text-[var(--color-muted-copy)]">
            {messages.guests.summaryGroupsHelp}
          </p>
        </div>
      </div>

      <div
        className={`grid gap-6 ${canEdit ? "xl:grid-cols-[0.82fr_1.18fr]" : "grid-cols-1"}`}
      >
        {canEdit ? (
          <Card
            className="scroll-mt-40 border-white/70 bg-[linear-gradient(160deg,rgba(255,255,255,0.9),rgba(255,243,247,0.82),rgba(255,248,232,0.84))] shadow-[0_30px_110px_rgba(233,60,172,0.08)]"
            ref={formRef}
          >
            <CardHeader>
              <CardTitle className="font-display text-3xl text-[var(--color-ink)]">
                {selectedGuest ? messages.guests.edit : messages.guests.add}
              </CardTitle>
            </CardHeader>
            <CardContent>
              <form className="space-y-3" onSubmit={onSubmit}>
                <div className="grid gap-3 sm:grid-cols-2">
                  <label className="space-y-1 text-sm text-[var(--color-ink)]">
                    <span>{messages.guests.firstName}</span>
                    <Input
                      placeholder={messages.guests.firstName}
                      aria-invalid={!!errors.firstName}
                      {...register("firstName")}
                    />
                    <FieldError error={errors.firstName} />
                  </label>
                  <label className="space-y-1 text-sm text-[var(--color-ink)]">
                    <span>{messages.guests.lastName}</span>
                    <Input
                      placeholder={messages.guests.lastName}
                      aria-invalid={!!errors.lastName}
                      {...register("lastName")}
                    />
                    <FieldError error={errors.lastName} />
                  </label>
                </div>
                <div className="grid gap-3 sm:grid-cols-2">
                  <label className="space-y-1 text-sm text-[var(--color-ink)]">
                    <span>{messages.guests.side}</span>
                    <select
                      className="h-10 w-full rounded-xl border px-3"
                      {...register("side")}
                    >
                      <option value="BRIDE">
                        {messages.enums.guestSide.BRIDE}
                      </option>
                      <option value="GROOM">
                        {messages.enums.guestSide.GROOM}
                      </option>
                      <option value="FAMILY">
                        {messages.enums.guestSide.FAMILY}
                      </option>
                      <option value="FRIENDS">
                        {messages.enums.guestSide.FRIENDS}
                      </option>
                    </select>
                  </label>
                  <label className="space-y-1 text-sm text-[var(--color-ink)]">
                    <span>{messages.guests.rsvp}</span>
                    <select
                      className="h-10 w-full rounded-xl border px-3"
                      {...register("rsvpStatus")}
                    >
                      <option value="PENDING">
                        {messages.enums.rsvpStatus.PENDING}
                      </option>
                      <option value="ATTENDING">
                        {messages.enums.rsvpStatus.ATTENDING}
                      </option>
                      <option value="DECLINED">
                        {messages.enums.rsvpStatus.DECLINED}
                      </option>
                    </select>
                  </label>
                </div>
                <div className="grid gap-3 sm:grid-cols-2">
                  <label className="space-y-1 text-sm text-[var(--color-ink)]">
                    <span>{messages.guests.payment}</span>
                    <select
                      className="h-10 w-full rounded-xl border px-3"
                      {...register("paymentCoverage")}
                    >
                      <option value="FULL">
                        {messages.guests.fullPayment}
                      </option>
                      <option value="HALF">
                        {messages.guests.halfPayment}
                      </option>
                    </select>
                  </label>
                  <div className="grid grid-cols-2 gap-3 rounded-xl border px-3 py-2 text-sm text-[var(--color-ink)]">
                    <label className="col-span-2 flex items-center gap-2">
                      <input
                        type="checkbox"
                        {...register("invitationReceived")}
                      />
                      {messages.guests.invitationReceived}
                    </label>
                    <label className="flex items-center gap-2">
                      <input
                        type="checkbox"
                        {...register("transportToVenue")}
                      />
                      {messages.guests.transportTo}
                    </label>
                    <label className="flex items-center gap-2">
                      <input
                        type="checkbox"
                        {...register("transportFromVenue")}
                      />
                      {messages.guests.transportFrom}
                    </label>
                  </div>
                </div>
                <label className="space-y-1 text-sm text-[var(--color-ink)]">
                  <span>{messages.guests.groupName}</span>
                  <Input
                    placeholder={messages.guests.groupName}
                    {...register("groupName")}
                  />
                  <p className="text-xs leading-5 text-[var(--color-muted-copy)]">
                    {messages.guests.groupHelp}
                  </p>
                </label>
                <div className="grid gap-3 sm:grid-cols-2">
                  <label className="space-y-1 text-sm text-[var(--color-ink)]">
                    <span>{messages.guests.invitedGuestCount}</span>
                    <Input
                      type="number"
                      min="1"
                      max="10"
                      {...register("invitedGuestCount", {
                        valueAsNumber: true,
                      })}
                    />
                  </label>
                  <div className="rounded-xl border border-dashed border-[var(--color-card-tint)] px-3 py-2 text-sm text-[var(--color-muted-copy)]">
                    {messages.guests.groupHelp}
                  </div>
                </div>
                <label className="space-y-1 text-sm text-[var(--color-ink)]">
                  <span>{messages.guests.email}</span>
                  <Input
                    type="email"
                    placeholder={messages.guests.email}
                    aria-invalid={!!errors.email}
                    {...register("email")}
                  />
                  <FieldError error={errors.email} />
                </label>
                <label className="space-y-1 text-sm text-[var(--color-ink)]">
                  <span>{messages.guests.phone}</span>
                  <Input
                    type="tel"
                    placeholder={messages.guests.phone}
                    aria-invalid={!!errors.phone}
                    {...register("phone")}
                  />
                  <FieldError error={errors.phone} />
                </label>
                <label className="space-y-1 text-sm text-[var(--color-ink)]">
                  <span>{messages.guests.dietaryLabel}</span>
                  <select
                    className="h-10 w-full rounded-xl border px-3"
                    {...register("dietaryRestriction")}
                  >
                    <option value="NONE">{messages.guests.noDiet}</option>
                    <option value="VEGETARIAN">
                      {messages.guests.vegetarian}
                    </option>
                    <option value="VEGAN">{messages.guests.vegan}</option>
                  </select>
                </label>
                <label className="space-y-1 text-sm text-[var(--color-ink)]">
                  <span>{messages.guests.notesLabel}</span>
                  <Input
                    placeholder={messages.guests.notes}
                    {...register("notes")}
                  />
                </label>
                <div className="flex gap-3">
                  <Button
                    className="rounded-full"
                    type="submit"
                    disabled={isSubmitting}
                  >
                    {selectedGuest
                      ? messages.guests.save
                      : messages.guests.create}
                  </Button>
                  {selectedGuest ? (
                    <Button
                      type="button"
                      variant="outline"
                      className="rounded-full"
                      onClick={() => {
                        setSelectedGuest(null);
                        reset(emptyGuestForm);
                      }}
                    >
                      {messages.guests.cancel}
                    </Button>
                  ) : null}
                </div>
              </form>
            </CardContent>
          </Card>
        ) : null}
        <Card className="border-white/70 bg-[linear-gradient(160deg,rgba(255,255,255,0.9),rgba(255,245,228,0.82),rgba(244,247,255,0.82))] shadow-[0_30px_110px_rgba(49,72,216,0.07)]">
          <CardHeader className="gap-4">
            <div className="flex items-center justify-between">
              <CardTitle className="font-display text-3xl text-[var(--color-ink)]">
                {messages.guests.list}
              </CardTitle>
              <div className="flex gap-2">
                <Button
                  size="sm"
                  variant="outline"
                  className="rounded-full bg-white/75"
                  onClick={() =>
                    void exportToExcel(filteredGuests, exportMessages)
                  }
                >
                  {messages.guests.exportExcel}
                </Button>
                <Button
                  size="sm"
                  variant="outline"
                  className="rounded-full bg-white/75"
                  onClick={() => exportToPdf(filteredGuests, exportMessages)}
                >
                  {messages.guests.exportPdf}
                </Button>
              </div>
            </div>
            <p className="text-sm text-[var(--color-muted-copy)]">
              {messages.guests.sortDescription}
            </p>
            <div className="grid gap-3 sm:grid-cols-[1fr_160px_160px]">
              <Input
                value={search}
                onChange={(event) => setSearch(event.target.value)}
                placeholder={messages.guests.search}
                aria-label={messages.guests.search}
              />
              <select
                className="h-10 rounded-xl border px-3"
                value={side}
                onChange={(event) => setSide(event.target.value)}
                aria-label={messages.guests.side}
              >
                <option value="ALL">{messages.guests.allSides}</option>
                <option value="BRIDE">{messages.enums.guestSide.BRIDE}</option>
                <option value="GROOM">{messages.enums.guestSide.GROOM}</option>
                <option value="FAMILY">
                  {messages.enums.guestSide.FAMILY}
                </option>
                <option value="FRIENDS">
                  {messages.enums.guestSide.FRIENDS}
                </option>
              </select>
              <select
                className="h-10 rounded-xl border px-3"
                value={group}
                onChange={(event) => setGroup(event.target.value)}
                aria-label={messages.guests.groupName}
              >
                <option value="ALL">{messages.guests.allGroups}</option>
                {uniqueGroups.map((g) => (
                  <option key={g} value={g}>
                    {g}
                  </option>
                ))}
              </select>
            </div>
          </CardHeader>
          <CardContent>
            {visibleGroups.length > 0 ? (
              <div className="mb-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">
                {visibleGroups.map((invitationGroup) => (
                  <div
                    key={invitationGroup.id}
                    className="rounded-[1.6rem] border border-white/70 bg-[linear-gradient(135deg,rgba(255,255,255,0.82),rgba(255,244,229,0.76),rgba(255,237,244,0.72))] p-4 shadow-[0_16px_40px_rgba(59,47,52,0.05)]"
                  >
                    <div>
                      <div>
                        <h3 className="font-display text-2xl text-[var(--color-ink)]">
                          {invitationGroup.name}
                        </h3>
                        <p className="text-sm text-[var(--color-muted-copy)]">
                          {messages.guests.groupSummary(
                            invitationGroup.memberCount,
                            invitationGroup.invitedGuestCount,
                          )}
                        </p>
                      </div>
                    </div>
                    <p className="mt-3 text-sm text-[var(--color-muted-copy)]">
                      {messages.guests.groupRsvpSummary(
                        invitationGroup.attendingCount,
                        invitationGroup.pendingCount,
                        invitationGroup.declinedCount,
                      )}
                    </p>
                  </div>
                ))}
              </div>
            ) : null}
            {/* Bulk action bar */}
            {canEdit && selectedIds.size > 0 && (
              <div className="mb-4 flex flex-wrap items-center gap-3 rounded-[1.4rem] border border-white/70 bg-[linear-gradient(135deg,rgba(255,255,255,0.82),rgba(255,244,229,0.74),rgba(255,237,244,0.7))] p-3 shadow-[0_14px_34px_rgba(59,47,52,0.05)]">
                <span className="text-sm font-medium text-[var(--color-ink)]">
                  {messages.guests.selected(selectedIds.size)}
                </span>
                <select
                  className="h-8 rounded-lg border px-2 text-sm"
                  value={bulkRsvp}
                  onChange={(e) =>
                    setBulkRsvp(
                      e.target.value as "PENDING" | "ATTENDING" | "DECLINED",
                    )
                  }
                >
                  <option value="ATTENDING">
                    {messages.enums.rsvpStatus.ATTENDING}
                  </option>
                  <option value="PENDING">
                    {messages.enums.rsvpStatus.PENDING}
                  </option>
                  <option value="DECLINED">
                    {messages.enums.rsvpStatus.DECLINED}
                  </option>
                </select>
                <Button size="sm" variant="outline" onClick={handleBulkRsvp}>
                  {messages.guests.bulkChangeRsvp}
                </Button>
                <Button
                  size="sm"
                  variant="outline"
                  onClick={handleBulkAssignGroup}
                >
                  {messages.guests.groupSelected}
                </Button>
                <Button size="sm" variant="outline" onClick={handleBulkUngroup}>
                  {messages.guests.ungroupSelected}
                </Button>
                <Button
                  size="sm"
                  variant="outline"
                  onClick={handleBulkDelete}
                  className="ml-auto text-red-600"
                >
                  {messages.guests.bulkDelete}
                </Button>
              </div>
            )}
            <div className="overflow-x-auto rounded-[1.6rem] border border-white/70 bg-white/70 shadow-[0_18px_55px_rgba(59,47,52,0.05)]">
              <Table>
                <TableHeader>
                  <TableRow>
                    {canEdit && (
                      <TableHead className="w-10">
                        <input
                          type="checkbox"
                          checked={
                            filteredGuests.length > 0 &&
                            selectedIds.size === filteredGuests.length
                          }
                          onChange={toggleAll}
                        />
                      </TableHead>
                    )}
                    <TableHead>{messages.guests.name}</TableHead>
                    <TableHead>{messages.guests.groupName}</TableHead>
                    <TableHead>{messages.guests.rsvp}</TableHead>
                    <TableHead>{messages.guests.diet}</TableHead>
                    <TableHead>{messages.guests.notesLabel}</TableHead>
                    <TableHead>{messages.guests.token}</TableHead>
                    <TableHead>{messages.guests.payment}</TableHead>
                    <TableHead>{messages.guests.invitationReceived}</TableHead>
                    <TableHead>{messages.guests.transport}</TableHead>
                    <TableHead>{messages.guests.table}</TableHead>
                    <TableHead>{messages.guests.contact}</TableHead>
                    <TableHead />
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {filteredGuests.map((guest, index) => {
                    const previousGuest = filteredGuests[index - 1];
                    const isNewSideSection =
                      !previousGuest || previousGuest.side !== guest.side;
                    const isNewGroupBlock =
                      guest.groupName &&
                      (!previousGuest ||
                        previousGuest.groupName !== guest.groupName ||
                        previousGuest.side !== guest.side);

                    return (
                      <Fragment key={guest.id}>
                        {isNewSideSection ? (
                          <TableRow className="bg-[var(--color-card-tint)]/35 hover:bg-[var(--color-card-tint)]/35">
                            <TableCell
                              colSpan={columnCount}
                              className="py-3 text-sm font-semibold uppercase tracking-[0.22em] text-[var(--color-dusty-rose)]"
                            >
                              {messages.enums.guestSide[guest.side]}
                            </TableCell>
                          </TableRow>
                        ) : null}
                        <TableRow
                          id={`guest-${guest.id}`}
                          className={`scroll-mt-40 ${isNewGroupBlock ? "border-t-[3px] border-t-[var(--color-card-tint)]" : ""}`}
                          onDoubleClick={() => canEdit && handleEdit(guest)}
                        >
                          {canEdit && (
                            <TableCell>
                              <input
                                type="checkbox"
                                checked={selectedIds.has(guest.id)}
                                onChange={() => toggleSelected(guest.id)}
                              />
                            </TableCell>
                          )}
                          <TableCell>
                            <div>
                              <p className="font-medium text-[var(--color-ink)]">
                                {guest.fullName}
                              </p>
                              <div className="mt-1 flex flex-wrap items-center gap-2 text-sm text-[var(--color-muted-copy)]">
                                <span>
                                  {messages.enums.guestSide[guest.side]}
                                </span>
                                {guest.groupName ? (
                                  <span className="rounded-full bg-[var(--color-card-tint)] px-2 py-0.5 text-xs font-medium uppercase tracking-[0.18em] text-[var(--color-dusty-rose)]">
                                    {guest.groupName}
                                  </span>
                                ) : null}
                              </div>
                            </div>
                          </TableCell>
                          <TableCell>
                            {guest.groupName || messages.guests.none}
                          </TableCell>
                          <TableCell>
                            <label className="flex items-center gap-2 text-sm text-[var(--color-ink)]">
                              <input
                                type="checkbox"
                                checked={guest.rsvpStatus === "ATTENDING"}
                                onChange={() => void handleRsvpToggle(guest)}
                              />
                              {messages.enums.rsvpStatus[guest.rsvpStatus]}
                            </label>
                          </TableCell>
                          <TableCell>
                            {guest.dietaryRestrictions[0] === "VEGETARIAN"
                              ? messages.guests.vegetarian
                              : guest.dietaryRestrictions[0] === "VEGAN"
                                ? messages.guests.vegan
                                : messages.guests.noDiet}
                          </TableCell>
                          <TableCell>
                            {guest.notes || messages.guests.none}
                          </TableCell>
                          <TableCell>{guest.rsvpToken}</TableCell>
                          <TableCell>
                            {guest.paymentCoverage === "HALF"
                              ? messages.guests.halfPayment
                              : messages.guests.fullPayment}
                          </TableCell>
                          <TableCell>
                            {guest.invitationReceived ? "Tak" : "Nie"}
                          </TableCell>
                          <TableCell>
                            {[
                              guest.transportToVenue
                                ? messages.guests.transportTo
                                : "",
                              guest.transportFromVenue
                                ? messages.guests.transportFrom
                                : "",
                            ]
                              .filter(Boolean)
                              .join(" / ") || messages.guests.none}
                          </TableCell>
                          <TableCell>
                            {guest.tableName ?? messages.guests.unassigned}
                          </TableCell>
                          <TableCell>{guest.email}</TableCell>
                          <TableCell className="space-x-2 text-right">
                            {canEdit ? (
                              <>
                                <Button
                                  size="sm"
                                  variant="outline"
                                  onClick={() => handleEdit(guest)}
                                >
                                  {messages.guests.editButton}
                                </Button>
                                <Button
                                  size="sm"
                                  variant="outline"
                                  onClick={() => handleDelete(guest.id)}
                                >
                                  {messages.guests.delete}
                                </Button>
                              </>
                            ) : null}
                          </TableCell>
                        </TableRow>
                      </Fragment>
                    );
                  })}
                </TableBody>
              </Table>
              {filteredGuests.length === 0 ? (
                <p className="py-8 text-center text-sm text-[var(--color-muted-copy)]">
                  {messages.guests.empty}
                </p>
              ) : null}
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};
