import { createHash } from "node:crypto";
import { hashSync } from "bcryptjs";

import type { PlannerState } from "@/lib/planner-domain";

const weddingId = "wedding-luna-fern";
const now = "2026-03-13T10:00:00.000Z";

export const DEMO_CREDENTIALS = {
  name: "Admin Demo",
  email: "admin@example.com",
  password: "Avatar3232!",
};

export const WITNESS_DEMO_CREDENTIALS = {
  name: "Witness Demo",
  email: "witness@example.com",
  password: "Avatar3232!",
};

export const createPlannerSeed = (): PlannerState => {
  const passwordHash = hashSync(DEMO_CREDENTIALS.password, 8);
  const state = {
    users: [
      {
        id: "user-primary",
        weddingId,
        name: DEMO_CREDENTIALS.name,
        email: DEMO_CREDENTIALS.email,
        role: "ADMIN",
        passwordHash,
        createdAt: now,
        updatedAt: now,
      },
    ],
    userInvitations: [],
    wedding: {
      id: weddingId,
      slug: "olivia-daniel",
      title: "Olivia & Daniel",
      coupleOneName: "Olivia",
      coupleTwoName: "Daniel",
      venueName: "Ivory Conservatory",
      venueAddress: "18 Garden Terrace, Warsaw",
      ceremonyDate: "2026-09-19T14:00:00.000Z",
      aboutText:
        "We met on a rainy afternoon in a bookshop and have been inseparable ever since. We can't wait to celebrate this next chapter with everyone we love.",
      dressCode: "Black tie optional",
      faqItems: JSON.stringify([
        {
          question: "Is there parking at the venue?",
          answer:
            "Yes, the Ivory Conservatory has a private lot with 80 spots. Overflow parking is available on Garden Terrace.",
        },
        {
          question: "Can I bring a plus-one?",
          answer:
            "Due to limited seating we ask that you only bring guests who were explicitly named on your invitation.",
        },
        {
          question: "What time should I arrive?",
          answer:
            "Doors open at 13:30 for a champagne welcome. The ceremony begins promptly at 14:00.",
        },
      ]),
      createdAt: now,
      updatedAt: now,
    },
    guests: [
      {
        id: "guest-1",
        weddingId,
        firstName: "Emma",
        lastName: "Hart",
        side: "BRIDE",
        rsvpStatus: "ATTENDING",
        dietaryRestrictions: ["Vegetarian"],
        tableId: "table-1",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "guest-2",
        weddingId,
        firstName: "Liam",
        lastName: "Hart",
        side: "BRIDE",
        rsvpStatus: "ATTENDING",
        dietaryRestrictions: [],
        tableId: "table-1",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "guest-3",
        weddingId,
        firstName: "Sofia",
        lastName: "Cole",
        side: "GROOM",
        rsvpStatus: "ATTENDING",
        dietaryRestrictions: ["Gluten free"],
        tableId: "table-2",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "guest-4",
        weddingId,
        firstName: "Henry",
        lastName: "Cole",
        side: "GROOM",
        rsvpStatus: "PENDING",
        dietaryRestrictions: [],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "guest-5",
        weddingId,
        firstName: "Charlotte",
        lastName: "Mills",
        side: "FAMILY",
        rsvpStatus: "DECLINED",
        dietaryRestrictions: [],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "guest-6",
        weddingId,
        firstName: "Noah",
        lastName: "Mills",
        side: "FRIENDS",
        rsvpStatus: "ATTENDING",
        dietaryRestrictions: [],
        tableId: "table-3",
        createdAt: now,
        updatedAt: now,
      },
    ],
    contacts: [
      {
        id: "contact-1",
        weddingId,
        guestId: "guest-1",
        email: "emma@example.com",
        phone: "+48 500 100 100",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "contact-2",
        weddingId,
        guestId: "guest-2",
        email: "liam@example.com",
        phone: "+48 500 100 101",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "contact-3",
        weddingId,
        guestId: "guest-3",
        email: "sofia@example.com",
        phone: "+48 500 100 102",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "contact-4",
        weddingId,
        guestId: "guest-4",
        email: "henry@example.com",
        phone: "+48 500 100 103",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "contact-5",
        weddingId,
        vendorId: "vendor-1",
        email: "events@ivoryconservatory.com",
        phone: "+48 600 200 200",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "contact-6",
        weddingId,
        vendorId: "vendor-2",
        email: "hello@roseatelier.com",
        phone: "+48 600 200 201",
        createdAt: now,
        updatedAt: now,
      },
    ],
    notes: [
      {
        id: "note-1",
        weddingId,
        guestId: "guest-1",
        content: "Prefers sparkling water and sits well with grandparents.",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "note-2",
        weddingId,
        guestId: "guest-4",
        content: "Reminder to call about plus-one before April.",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "note-3",
        weddingId,
        vendorId: "vendor-2",
        content: "Bouquet palette approved in rose, peach, and butter tones.",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "note-4",
        weddingId,
        taskId: "task-2",
        content: "Need final proof from stationer before printing.",
        createdAt: now,
        updatedAt: now,
      },
    ],
    weddingTables: [
      {
        id: "table-1",
        weddingId,
        name: "Garden Table",
        capacity: 4,
        positionX: 20,
        positionY: 20,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "table-2",
        weddingId,
        name: "Conservatory Table",
        capacity: 4,
        positionX: 340,
        positionY: 20,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "table-3",
        weddingId,
        name: "Champagne Table",
        capacity: 4,
        positionX: 660,
        positionY: 20,
        createdAt: now,
        updatedAt: now,
      },
    ],
    seats: [
      {
        id: "seat-1",
        weddingId,
        tableId: "table-1",
        guestId: "guest-1",
        label: "A1",
        position: 1,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "seat-2",
        weddingId,
        tableId: "table-1",
        guestId: "guest-2",
        label: "A2",
        position: 2,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "seat-5",
        weddingId,
        tableId: "table-1",
        label: "A3",
        position: 3,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "seat-6",
        weddingId,
        tableId: "table-1",
        label: "A4",
        position: 4,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "seat-3",
        weddingId,
        tableId: "table-2",
        guestId: "guest-3",
        label: "B1",
        position: 1,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "seat-7",
        weddingId,
        tableId: "table-2",
        label: "B2",
        position: 2,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "seat-8",
        weddingId,
        tableId: "table-2",
        label: "B3",
        position: 3,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "seat-9",
        weddingId,
        tableId: "table-2",
        label: "B4",
        position: 4,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "seat-4",
        weddingId,
        tableId: "table-3",
        guestId: "guest-6",
        label: "C1",
        position: 1,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "seat-10",
        weddingId,
        tableId: "table-3",
        label: "C2",
        position: 2,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "seat-11",
        weddingId,
        tableId: "table-3",
        label: "C3",
        position: 3,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "seat-12",
        weddingId,
        tableId: "table-3",
        label: "C4",
        position: 4,
        createdAt: now,
        updatedAt: now,
      },
    ],
    vendorCategories: [
      {
        id: "vendor-category-1",
        weddingId,
        name: "Venue",
        type: "VENUE",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "vendor-category-2",
        weddingId,
        name: "Floral Design",
        type: "FLORAL",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "vendor-category-3",
        weddingId,
        name: "Photography",
        type: "PHOTO",
        createdAt: now,
        updatedAt: now,
      },
    ],
    vendors: [
      {
        id: "vendor-1",
        weddingId,
        categoryId: "vendor-category-1",
        name: "Ivory Conservatory",
        cost: 9200,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "vendor-2",
        weddingId,
        categoryId: "vendor-category-2",
        name: "Rose Atelier",
        cost: 2100,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "vendor-3",
        weddingId,
        categoryId: "vendor-category-3",
        name: "Northlight Stories",
        cost: 3400,
        createdAt: now,
        updatedAt: now,
      },
    ],
    budgetCategories: [
      {
        id: "budget-1",
        weddingId,
        name: "Venue",
        plannedAmount: 10000,
        color: "#D89BAE",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "budget-2",
        weddingId,
        name: "Floral",
        plannedAmount: 2500,
        color: "#E8B4A0",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "budget-3",
        weddingId,
        name: "Photography",
        plannedAmount: 4000,
        color: "#A1C6B4",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "budget-4",
        weddingId,
        name: "Music",
        plannedAmount: 1800,
        color: "#8EA6D1",
        createdAt: now,
        updatedAt: now,
      },
    ],
    expenses: [
      {
        id: "expense-1",
        weddingId,
        categoryId: "budget-1",
        name: "Venue booking",
        estimateMin: 9000,
        estimateMax: 10000,
        actualAmount: 9200,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "expense-2",
        weddingId,
        categoryId: "budget-2",
        name: "Floral design",
        estimateMin: 1800,
        estimateMax: 2500,
        actualAmount: 2100,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "expense-3",
        weddingId,
        categoryId: "budget-3",
        name: "Photo coverage",
        estimateMin: 3000,
        estimateMax: 4000,
        actualAmount: 3400,
        createdAt: now,
        updatedAt: now,
      },
    ],
    payments: [
      {
        id: "payment-1",
        weddingId,
        expenseId: "expense-1",
        amount: 7000,
        paidAt: "2026-02-01T12:00:00.000Z",
        notes: "Venue deposit",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "payment-2",
        weddingId,
        expenseId: "expense-2",
        amount: 900,
        paidAt: "2026-02-12T12:00:00.000Z",
        notes: "Floral retainer",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "payment-3",
        weddingId,
        expenseId: "expense-3",
        amount: 1700,
        paidAt: "2026-02-21T12:00:00.000Z",
        notes: "Photo booking",
        createdAt: now,
        updatedAt: now,
      },
    ],
    tasks: [
      {
        id: "task-1",
        weddingId,
        title: "Confirm final menu tasting",
        description:
          "Lock the tasting date with the chef and send dietary notes.",
        dueDate: "2026-04-08T12:00:00.000Z",
        priority: "HIGH",
        status: "IN_PROGRESS",
        assignee: "COUPLE",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "task-2",
        weddingId,
        title: "Approve invitation proof",
        description: "Final review before the print run starts.",
        dueDate: "2026-03-29T12:00:00.000Z",
        priority: "HIGH",
        status: "TODO",
        assignee: "BRIDE",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "task-3",
        weddingId,
        title: "Book string quartet rehearsal",
        description: "Reserve a one-hour rehearsal in the venue atrium.",
        dueDate: "2026-04-18T12:00:00.000Z",
        priority: "MEDIUM",
        status: "DONE",
        assignee: "WITNESSES",
        createdAt: now,
        updatedAt: now,
      },
    ],
    timelineEvents: [
      {
        id: "timeline-1",
        weddingId,
        title: "Guest arrival",
        description: "Champagne welcome with string quartet.",
        startsAt: "2026-09-19T13:30:00.000Z",
        location: "Ivory Conservatory foyer",
        visibleToGuests: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "timeline-2",
        weddingId,
        title: "Ceremony",
        description: "Garden ceremony beneath the glasshouse arches.",
        startsAt: "2026-09-19T14:00:00.000Z",
        location: "Rose courtyard",
        visibleToGuests: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "timeline-3",
        weddingId,
        title: "Dinner service",
        description: "Three-course plated dinner and speeches.",
        startsAt: "2026-09-19T17:30:00.000Z",
        location: "Main hall",
        visibleToGuests: true,
        createdAt: now,
        updatedAt: now,
      },
    ],
    rsvps: [
      {
        id: "rsvp-1",
        weddingId,
        guestId: "guest-1",
        status: "ATTENDING",
        guestCount: 1,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "rsvp-2",
        weddingId,
        guestId: "guest-3",
        status: "ATTENDING",
        guestCount: 1,
        createdAt: now,
        updatedAt: now,
      },
    ],
  } as unknown as PlannerState;

  state.users.push({
    id: "user-witness-demo",
    weddingId,
    name: WITNESS_DEMO_CREDENTIALS.name,
    email: WITNESS_DEMO_CREDENTIALS.email,
    role: "WITNESS",
    passwordHash: hashSync(WITNESS_DEMO_CREDENTIALS.password, 8),
    createdAt: now,
    updatedAt: now,
  });

  const groupMap: Record<string, string> = {
    "guest-1": "Hart Family",
    "guest-2": "Hart Family",
    "guest-3": "Cole Family",
    "guest-4": "Cole Family",
  };

  state.guests = state.guests.map((guest) => ({
    ...guest,
    rsvpToken: createHash("sha256")
      .update(guest.id)
      .digest("hex")
      .slice(0, 10)
      .toUpperCase(),
    paymentCoverage: "FULL",
    invitationReceived: true,
    transportToVenue: false,
    transportFromVenue: false,
    groupName: groupMap[guest.id] ?? "",
  }));
  state.budgetCategories = state.budgetCategories.map((category) => ({
    ...category,
    notes: "",
  }));
  state.expenses = state.expenses.map((expense) => ({
    ...expense,
    notes: "",
  }));

  return state;
};
